#!/bin/sh
set -e
if systemctl >/dev/null 2>/dev/null; then
	OPTS=""

	if [ -n "$D" ]; then
		OPTS="--root=$D"
	fi

	if [ "enable" = "enable" ]; then
		for service in weston.service weston.socket; do
			systemctl ${OPTS} enable "$service"
		done
	fi

	if [ -z "$D" ]; then
		systemctl daemon-reload
		systemctl preset weston.service weston.socket

		if [ "enable" = "enable" ]; then
			systemctl --no-block restart weston.service weston.socket
		fi
	fi
fi
